AWSTemplateFormatVersion: "2010-09-09"
Description: "Part 7: Security Auditing (AWS CloudTrail + Log Bucket)"

Resources:
  # 1. Secure Bucket for Audit Logs
  AuditLogBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Unique Name
      BucketName: !Sub "audit-logs-${AWS::AccountId}-${AWS::Region}"
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # 2. Bucket Policy
  AuditLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AuditLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # Allow CloudTrail to check bucket permissions
          - Sid: AWSCloudTrailAclCheck
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !GetAtt AuditLogBucket.Arn
          # Allow CloudTrail to write log files
          - Sid: AWSCloudTrailWrite
            Effect: Allow
            Principal:
              Service: cloudtrail.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${AuditLogBucket.Arn}/AWSLogs/${AWS::AccountId}/*"
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control

  # 3. The CloudTrail Tracker
  MySecurityTrail:
    Type: AWS::CloudTrail::Trail
    DependsOn: AuditLogBucketPolicy
    Properties:
      TrailName: SecureMigration-AuditTrail
      S3BucketName: !Ref AuditLogBucket
      IsLogging: true
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true # Tracks IAM changes
      IsMultiRegionTrail: true

Outputs:
  TrailARN:
    Description: The ARN of the Security Trail
    Value: !GetAtt MySecurityTrail.Arn
  LogBucketName:
    Description: Bucket where logs are stored
    Value: !Ref AuditLogBucket
